### ISSUE TITLE
Reflection is not aspect ratio independent

### ISSUE THREAD

**Issue by Gordan1000** [Dioinecail/urp-planar-sample#1]
This works great but with one big issue. Reflection distorts when rendering resolution is not in 16:9 aspect ratio. So, when running at 21:9 or free aspect ratio the reflection is stretched or shrinked.

**Comment by Dioinecail** [comment]
oh yeah, you're right, because the render texture is premade as 1920x1080, i should change it to create at runtime from screen resolution

**Comment by Dioinecail** [comment]
Tweaked the code a little bit, now it will not be distorted on non 16:9 resolutions
